### ISSUE TITLE
How do I get the pre-loaded cocktails and ingredients?

### ISSUE THREAD

**Issue by samwise22** [karlomikus/bar-assistant#176]
I used docker compose to build my instance and its empty. Is there a change I can make to the compose file to re-build or a way to import them after the fact?

**Comment by karlomikus** [comment]
Hello,
If the database file is present in the volume it won't run initial database seeding. You can run `docker compose exec bar-assistant php artisan bar:open` manually.

**Comment by samwise22** [comment]
hi, thanks so much for trying to help. Unfortunately I get the below error when I try to run that command

```
Opening the bar in production environment...
Testing your search driver connection [meilisearch]...
[2023-09-17 15:26:31] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.id (Connection: sqlite, SQL: insert into "users" ("email", "email_verified_at", "id", "is_admin", "name", "password", "remember_token", "search_api_key") values (default@localhost.com, ?, 1, 0, Bas Assistant, , ?, ?), (admin@example.com, 2023-09-17 15:26:31, 2, 1, Bartender, $2y$10$XGQMEN2d4X2h0PN793L6M.zCTURRzrmAsSNd264Q0zeNbL5V6fQja, 8M4G0FjUcz, 61825af3b82723389b2bef3abf779d24cf13ad9e3fe833a6d1879c598d19790d)) {"exception":"[object] (Illuminate\\Database\\UniqueConstraintViolationException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.id (Connection: sqlite, SQL: insert into \"users\" (\"email\", \"email_verified_at\", \"id\", \"is_admin\", \"name\", \"password\", \"remember_token\", \"search_api_key\") values (default@localhost.com, ?, 1, 0, Bas Assistant, , ?, ?), (admin@example.com, 2023-09-17 15:26:31, 2, 1, Bartender, $2y$10$XGQMEN2d4X2h0PN793L6M.zCTURRzrmAsSNd264Q0zeNbL5V6fQja, 8M4G0FjUcz, 61825af3b82723389b2bef3abf779d24cf13ad9e3fe833a6d1879c598d19790d)) at /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php:796)
[stacktrace]
#0 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#2 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->statement()
#3 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3336): Illuminate\\Database\\Connection->insert()
#4 /var/www/cocktails/app/Console/Commands/BarOpen.php(72): Illuminate\\Database\\Query\\Builder->insert()
#5 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Kami\\Cocktail\\Console\\Commands\\BarOpen->handle()
#6 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#11 /var/www/cocktails/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#12 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/cocktails/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#14 /var/www/cocktails/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/cocktails/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#17 /var/www/cocktails/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 {main}

[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.id at /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)
[stacktrace]
#0 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): PDOStatement->execute()
#1 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#4 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->statement()
#5 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3336): Illuminate\\Database\\Connection->insert()
#6 /var/www/cocktails/app/Console/Commands/BarOpen.php(72): Illuminate\\Database\\Query\\Builder->insert()
#7 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Kami\\Cocktail\\Console\\Commands\\BarOpen->handle()
#8 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#13 /var/www/cocktails/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#14 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/cocktails/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#16 /var/www/cocktails/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/cocktails/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#19 /var/www/cocktails/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"}

In Connection.php line 796:

  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.id (Connection: sqlite, SQL: insert into "users" ("email", "emai
  l_verified_at", "id", "is_admin", "name", "password", "remember_token", "search_api_key") values (default@localhost.com, ?, 1, 0, Bas Assistant, , ?
  , ?), (admin@example.com, 2023-09-17 15:26:31, 2, 1, Bartender, $2y$10$XGQMEN2d4X2h0PN793L6M.zCTURRzrmAsSNd264Q0zeNbL5V6fQja, 8M4G0FjUcz, 61825af3b8
  2723389b2bef3abf779d24cf13ad9e3fe833a6d1879c598d19790d))


In Connection.php line 580:

  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.id
```

**Comment by samwise22** [comment]
Ah I see, I needed to start from scratch to run this command. I'm all set now - thanks :-)
