### ISSUE TITLE
Initial Setup: Cocktails appear in list, but individual pages are blank

### ISSUE THREAD

**Issue by sameleff** [karlomikus/bar-assistant#193]
I've been encountering a very strange issue: as far as I can tell (inspection of database in system files, viewing /cocktails webpage, querying API, etc.) all of the cocktails are loaded after initial startup. However, when I click on a particular cocktail, the page that opens is blank. I cannot find any issues in any of the logs for bar assistant, nor swag. Config files and photos below.

The default credentials load correctly, and I can access the API and salt-rim webpage. Additionally, I am using swag to proxy to my custom duckdns domain with ssl certs. This all works as far as I can tell: no errors in swag etc.

docker-compose.yml:
```
version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - /mnt/user/appdata/meilisearch_data:/meili_data
    networks:
      - nginxnet

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - nginxnet

  bar-assistant:
    image: barassistant/server:latest
    depends_on:
      - meilisearch
      - redis
    environment:
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/appdata/barassistant_data:/var/www/cocktails/storage/bar-assistant
    networks:
      - nginxnet

  salt-rim:
    image: barassistant/salt-rim:latest
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=$BAR_NAME
      - DESCRIPTION=$BAR_DESCRIPTION
      - DEFAULT_LOCALE=en-US
    ports:
      - 8082:8080
    restart: unless-stopped
    networks:
      - nginxnet

#volumes:
#  bar_data:
#  meilisearch_data:

networks:
  nginxnet:
    external: true
```

.env file
```
# Your Meilisearch master key
# Find out more here: https://docs.meilisearch.com/learn/getting_started/quick_start.html#securing-meilisearch
MEILI_MASTER_KEY=my_long_key

# Base URL of the application
# You should update this value to the one you are using (ex: http://192.168.100.100, https://my-personal-bar.com)
# In this case it's the URL and port that is exposed in webserver service
# The value MUST be without trailing slash
BASE_URL=https://mydomain.duckdns.org
# BASE_URL=http://192.168.1.38:8082

# Meilisearch server instance URL, change if you are using different host from base url, otherwise leave as default
MEILISEARCH_URL=https://mydomain.duckdns.org/search
# MEILISEARCH_URL=http://192.168.1.38:7700

# Bar Assistant server instance URL, change if you are using different host from base url, otherwise leave as default
API_URL=https://mydomain.duckdns.org/bar
# API_URL=http://192.168.1.38:3000

# (Optional) Bar name
BAR_NAME="Home Bar"

# (Optional) Short bar description
BAR_DESCRIPTION=
```

swag barassistant.config
```
server {
    listen 443 ssl http2;
    #listen [::]:443 ssl http2;

    server_name mydomain.duckdns.org;

    include /config/nginx/ssl.conf;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
    
    location = /robots.txt  {
        access_log off;
        log_not_found off;
    }

    client_max_body_size 100M;

    location / {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass http://192.168.1.38:8082;

    }

    location ~/bar(?<sub_dir>.*)$ {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass http://192.168.1.38:3000$sub_dir;

    }

    location ~/search(?<sub_dir>.*)$ {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        proxy_pass http://192.168.1.38:7700$sub_dir;

    }
}
```

swag access.log
```
<my public IP> - - [27/Sep/2023:12:04:24 -0400] "GET /bar/api/user HTTP/2.0" 200 313 "https://mydomain.duckdns.org/cocktails" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
<my public IP> - - [27/Sep/2023:12:04:24 -0400] "GET /bar/api/cocktails/20th-century?navigation=true HTTP/2.0" 200 1855 "https://mydomain.duckdns.org/cocktails/20th-century" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
```

bar-assistant logs
```
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  Application key set successfully.  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  The [public/storage] link has been connected to [storage/app/public].  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  The [public/uploads] link has been connected to [storage/bar-assistant/uploads].  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  Nothing to migrate.  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  | Updating search index settings...
bar_assistant-bar-assistant-1  | Syncing cocktails and ingredients to meilisearch...
bar_assistant-bar-assistant-1  | Adding routes and config to cache...
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  Configuration cached successfully.  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  |    INFO  Routes cached successfully.  
bar_assistant-bar-assistant-1  | 
bar_assistant-bar-assistant-1  | !***************************!
bar_assistant-bar-assistant-1  | !    Application ready      !
bar_assistant-bar-assistant-1  | !***************************!
bar_assistant-bar-assistant-1  | [27-Sep-2023 16:44:08] NOTICE: fpm is running, pid 34
bar_assistant-bar-assistant-1  | [27-Sep-2023 16:44:08] NOTICE: ready to handle connections
```

salt-rim logs are empty

meilisearch logs
```
Config file path:       "none"
Database path:          "./data.ms"
Server listening on:    "http://0.0.0.0:7700"
Environment:            "production"
Commit SHA:             "4b953d62fbab81278324e71b4037eb06355dd49a"
Commit date:            "2023-04-13T16:24:16+00:00"
Package version:        "1.1.1"

Thank you for using Meilisearch!


We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html

Anonymous telemetry:    "Enabled"
Instance UID:           "5817f753-0af2-4d80-b803-9b05f6f066f8"

A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.

Documentation:          https://docs.meilisearch.com
Source code:            https://github.com/meilisearch/meilisearch
Contact:                https://docs.meilisearch.com/resources/contact.html

[2023-09-27T16:44:07Z INFO  actix_server::builder] Starting 6 workers
[2023-09-27T16:44:07Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "PATCH /indexes/cocktails/settings HTTP/1.1" 202 128 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.003643
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "PATCH /indexes/cocktails/settings/pagination HTTP/1.1" 202 128 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.002387
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "PATCH /indexes/ingredients/settings HTTP/1.1" 202 129 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.003103
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "PATCH /indexes/ingredients/settings/pagination HTTP/1.1" 202 130 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.002134
[2023-09-27T16:44:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2023-09-27T16:44:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2023-09-27T16:44:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "POST /indexes/cocktails/documents?primaryKey=id HTTP/1.1" 202 138 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.005143
[2023-09-27T16:44:08Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 112, number_of_documents: 112 }
[2023-09-27T16:44:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2023-09-27T16:44:08Z INFO  actix_web::middleware::logger] 172.18.0.6 "POST /indexes/ingredients/documents?primaryKey=id HTTP/1.1" 202 140 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.004026
[2023-09-27T16:44:08Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 126, number_of_documents: 126 }
[2023-09-27T16:44:08Z INFO  index_scheduler] A batch of tasks was successfully completed.
[2023-09-27T16:44:12Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /version HTTP/1.1" 200 118 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.000806
[2023-09-27T16:53:28Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /version HTTP/1.1" 200 118 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.000384
[2023-09-27T16:53:29Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /version HTTP/1.1" 200 118 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.000388
[2023-09-27T16:53:30Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /version HTTP/1.1" 200 118 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.000439
[2023-09-27T16:53:31Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /version HTTP/1.1" 200 118 "-" "Meilisearch Laravel Scout (v9.8.1);Meilisearch PHP (v1.3.0)" 0.000369
```

redis logs
```
1:C 27 Sep 2023 16:44:07.648 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 27 Sep 2023 16:44:07.648 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 Sep 2023 16:44:07.648 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 Sep 2023 16:44:07.648 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 27 Sep 2023 16:44:07.648 * monotonic clock: POSIX clock_gettime
1:M 27 Sep 2023 16:44:07.649 * Running mode=standalone, port=6379.
1:M 27 Sep 2023 16:44:07.649 * Server initialized
1:M 27 Sep 2023 16:44:07.649 * Ready to accept connections tcp
1:M 27 Sep 2023 16:53:29.242 * 100 changes in 300 seconds. Saving...
1:M 27 Sep 2023 16:53:29.242 * Background saving started by pid 20
20:C 27 Sep 2023 16:53:29.251 * DB saved on disk
20:C 27 Sep 2023 16:53:29.251 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 27 Sep 2023 16:53:29.342 * Background saving terminated with success
```

**Comment by sameleff** [comment]
Forgot to include photos, they should be attached to this comment. They should help to illustrate that this issue only exists with individual cocktails, and not with ingredients.

![Cocktails Page](https://github.com/karlomikus/bar-assistant/assets/105563130/e33ecc40-ba9f-4242-bb7a-c12dc07edac5)
![20th Century Cocktail Page](https://github.com/karlomikus/bar-assistant/assets/105563130/b104d06b-0554-4dec-ad2a-c913865d248c)
![Absinthe Incredient Page](https://github.com/karlomikus/bar-assistant/assets/105563130/82e3d05d-d047-4d9c-8658-93589389243e)

**Comment by zhdenny** [comment]
Sometimes I have to clear browser cache/data and try again if this sorta thing happens

**Comment by sameleff** [comment]
> Sometimes I have to clear browser cache/data and try again if this sorta thing happens

No dice, unfortunately. I even tried using a new web browser (that hadn't previously been used to access the site).

**Comment by karlomikus** [comment]
Are there any errors in your browser console?

**Comment by sameleff** [comment]
Here are the browser logs. The first two sections (Lockdown failed & protecting intrinsics failed) appear when I first access the home page (right after logging in, so Shelf). If I click "Cocktails", no additional errors appear. The last one (TypeError) occurs when I click on an individual cocktail, in this case Adonis.

```
<html>
<body>
<!--StartFragment--><div tabindex="-1" class="console-message-wrapper console-from-api console-error-level" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3 Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-run.js:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">lockdown-run.js:17</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Lockdown failed: <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: At intrinsics.Object.groupBy expected boolean not function
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at isAllowedPropertyValue (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:53384" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:53384</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at isAllowedProperty (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:53807" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:53807</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at visitProperties (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:55095" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:55095</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at isAllowedPropertyValue (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:53041" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:53041</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at isAllowedProperty (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:53807" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:53807</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at visitProperties (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:55095" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:55095</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:55523" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:55523</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at repairIntrinsics (<span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:144597" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:144597</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-install.js:1:145462" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-install.js:1:145462</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">  at <span class="devtools-link ignore-list-link" role="link" tabindex="-1" title="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-run.js:4:3" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">lockdown-run.js:4:3</span></span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | (anonymous) | @ | lockdown-run.js:17
-- | -- | -- | --


</span></div></div></div></div></div><!--EndFragment-->
</body>
</html>
```

**Comment by karlomikus** [comment]
Seems like your swag setup strips query string parameters, from your logs:

<my public IP> - - [27/Sep/2023:12:04:24 -0400] "GET **/bar/api/cocktails/20th-century?navigation=true** HTTP/2.0" 200 1855 "**https://mydomain.duckdns.org/cocktails/20th-century**" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

You are missing `?navigation=true` in duckdns url, that's why some data is missing and the page breaks

**Comment by sameleff** [comment]
That makes total sense based on some other issues we've seen. However, I have no idea how to fix it since I am (clearly) an NGINX novice.

Ideally, we were hoping that the url's would display in this way:
base_url: mydomain.duckdns.org
bar (api) url: mydomain.duckdns.org/bar
search url: mydomain.duckdns.org/search

I followed the bottom answer on [this](https://serverfault.com/questions/792326/nginx-proxy-pass-using-subfolder) post in order to attempt to make this work. This method is shown in the .env file & nginx barassistant conf I included in my original post. Under this config, as I mentioned, everything appears to be able to talk to each other, but I think the `(?<sub_dir>.*)$` command must be filtering out queries. Any idea what I need to change?

I tried following the advice from the top answer on [this](https://serverfault.com/questions/840654/nginx-map-subdomain-to-a-subdirectory-on-proxied-server) post, but it didn't work. I also tried appending $request_uri (both with the $sub_dir method and without it).

**Comment by sameleff** [comment]
Just wanted to circle back...we got it working! Seriously, thanks for all your help. For anyone else that comes across this while trying to pass these services to a subdomain in this format:

home: mydomain.duckdns.org
bar (which is the api): mydomain.duckdns.org/bar
search: mydomain.duckdns.org/search

in your .env file, you should set the variables to the respective domains you want a user to see, e.g. https://mydomain.duckdns.org/search for meilisearch.

In your nginx conf, include the following 3 location blocks, replacing everything between <> with your information:

```
location / {
        proxy_pass http://<your host IP>:<salt-rim port>/;
    }

    location ~ ^/bar/(.*)$ {
        proxy_pass http://<your host IP>:<bar assistant port>/$1$is_args$args;

    }

    location ~ ^/search/(.*)$ {
        proxy_pass http://<your host IP>:<meilisearch port>/$1$is_args$args;
    }
```
