### ISSUE TITLE
Cocktail list empty/search not working

### ISSUE THREAD

**Issue by lewisd32** [karlomikus/bar-assistant#369]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
With a fresh installation and a new bar, navigating to the Cocktails tab shows no cocktails, but `Showing 25/306 results` at the bottom.
(Maybe I've done something wrong setting this up, but other than the browser console errors mentioned below, I can't find any other error logs.)

**To Reproduce**
Start a fresh installation with the versions below.
Navigate to the Cocktails page.

**Versions:**
 - Bar Assistant: 4.1.0
 - Salt Rim: 3.4.1
 - Meiiesearch: 1.8.4
 - Browser: Chrome, Windows 10

**Additional context, log outputs...**
DevTools shows `/bar/api/cocktails?per_page=25&page=1&sort=-created_at&&include=ratings%2Cingredients.ingredient%2Ctags%2Cimages` being requested, and the response payload contains cocktails.
Changing the dropdown to 50 or 100 per page shows the query `per_page` field changing correctly, but the response payload is always the same size, 6.9kB, and the page keeps showing no cocktails with `Showing 25/306 results` at the bottom. The next-page button doesn't change the page number. (A similar issue on the ingredients page.)

There are no log files at all in `/var/www/cocktails/storage/logs` in the container.

I see errors in the browser console when on the cocktails page:
```
TypeError: Cannot read properties of undefined (reading 'user')
    at CocktailsView-CgiCipXf.js:1:4140
    at Object.n [as default] (index-DZ1_cK56.js:14:3963)
    at Proxy.<anonymous> (index-DZ1_cK56.js:27:15628)
    at uo (index-DZ1_cK56.js:15:33447)
    at Rs.z [as fn] (index-DZ1_cK56.js:15:25098)
    at Rs.run (index-DZ1_cK56.js:10:1741)
    at N (index-DZ1_cK56.js:15:25487)
    at M (index-DZ1_cK56.js:15:24087)
    at A (index-DZ1_cK56.js:15:23878)
    at m (index-DZ1_cK56.js:15:20735)

index-DZ1_cK56.js:14 TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at Proxy.mounted (CocktailsView-CgiCipXf.js:1:2838)
    at index-DZ1_cK56.js:15:7407
    at Di (index-DZ1_cK56.js:14:1385)
    at lr (index-DZ1_cK56.js:14:1456)
    at t.__weh.t.__weh (index-DZ1_cK56.js:15:7287)
    at $o (index-DZ1_cK56.js:14:2966)
    at ig (index-DZ1_cK56.js:14:3275)

TypeError: Cannot read properties of undefined (reading 'user')
    at CocktailsView-CgiCipXf.js:1:4140
    at Object.n [as default] (index-DZ1_cK56.js:14:3963)
    at Proxy.<anonymous> (index-DZ1_cK56.js:27:15628)
    at uo (index-DZ1_cK56.js:15:33447)
    at Rs.z [as fn] (index-DZ1_cK56.js:15:24588)
    at Rs.run (index-DZ1_cK56.js:10:1741)
    at Rs.runIfDirty (index-DZ1_cK56.js:10:2051)
    at Di (index-DZ1_cK56.js:14:1393)
    at ig (index-DZ1_cK56.js:14:3146)
```

**Comment by karlomikus** [comment]
Hello,
The only `user` read on cocktails index is the one coming from the current app state. Can you try logging out and logging in back again and see if that fixes it.

**Comment by lewisd32** [comment]
Hello. I tried signing in fresh in an ingognito tab but I'm seeing the same thing. As soon as I "select bar" I get this in the console after the (amazing) ASCII art:
```
TypeError: Cannot read properties of undefined (reading 'user')
    at CocktailListContainer-8rbN-ap3.js:1:1375
    at Object.n [as default] (index-DZ1_cK56.js:14:3963)
    at Proxy.<anonymous> (index-DZ1_cK56.js:27:15628)
    at uo (index-DZ1_cK56.js:15:33447)
    at Rs.z [as fn] (index-DZ1_cK56.js:15:25098)
    at Rs.run (index-DZ1_cK56.js:10:1741)
    at N (index-DZ1_cK56.js:15:25487)
    at M (index-DZ1_cK56.js:15:24087)
    at A (index-DZ1_cK56.js:15:23878)
    at m (index-DZ1_cK56.js:15:20735)

TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at Proxy.mounted (CocktailListContainer-8rbN-ap3.js:1:807)
    at index-DZ1_cK56.js:15:7407
    at Di (index-DZ1_cK56.js:14:1385)
    at lr (index-DZ1_cK56.js:14:1456)
    at t.__weh.t.__weh (index-DZ1_cK56.js:15:7287)
    at $o (index-DZ1_cK56.js:14:2966)
    at ig (index-DZ1_cK56.js:14:3275)

TypeError: Cannot read properties of undefined (reading 'user')
    at CocktailListContainer-8rbN-ap3.js:1:1375
    at Object.n [as default] (index-DZ1_cK56.js:14:3963)
    at Proxy.<anonymous> (index-DZ1_cK56.js:27:15628)
    at uo (index-DZ1_cK56.js:15:33447)
    at Rs.z [as fn] (index-DZ1_cK56.js:15:25098)
    at Rs.run (index-DZ1_cK56.js:10:1741)
    at N (index-DZ1_cK56.js:15:25487)
    at M (index-DZ1_cK56.js:15:24087)
    at A (index-DZ1_cK56.js:15:23878)
    at m (index-DZ1_cK56.js:15:20735)

TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at Proxy.mounted (CocktailListContainer-8rbN-ap3.js:1:807)
    at index-DZ1_cK56.js:15:7407
    at Di (index-DZ1_cK56.js:14:1385)
    at lr (index-DZ1_cK56.js:14:1456)
    at t.__weh.t.__weh (index-DZ1_cK56.js:15:7287)
    at $o (index-DZ1_cK56.js:14:2966)
    at ig (index-DZ1_cK56.js:14:3275)
```

There are no errors in the console when I login, nothing until I "select bar". In the network tab of DevTools, all the calls return 200, and all the fetch calls are getting JSON, not HTML. (Some were getting HTML when I had nginx set up wrong at first, but that was before I was ever able to register and login.)

I tried the same thing in Firefox, and I see the same problem (empty list) but different errors in the console. It prints this _many_ times, then a different error many times:
```
TypeError: e.cocktail.rating is undefined
    default https://redacted.redacted.abc/assets/CocktailListContainer-8rbN-ap3.js:1
    n https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    setup https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    uo https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    E https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    T https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    E https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    T https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    E https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    _ https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    S https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    R https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    T https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    runIfDirty https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    Di https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    ig https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    promise callback*ng https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    Ku https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    scheduler https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    trigger https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    Bu https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    Nr https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    set https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    set https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    created https://redacted.redacted.abc/assets/HomeView-CPAtq689.js:1
    promise callback*created https://redacted.redacted.abc/assets/HomeView-CPAtq689.js:1
    Di https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    lr https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    nf https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    y0 https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    rv https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    J0 https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    tv https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    E https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    _ https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    S https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    E https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    T https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    N https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    M https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    A https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    m https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    z https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    run https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    runIfDirty https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    Di https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    ig https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    promise callback*ng https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    xo https://redacted.redacted.abc/assets/index-DZ1_cK56.js:14
    Yg https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    scheduler https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    scheduler https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    trigger https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    Bu https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    notify https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    trigger https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    set value https://redacted.redacted.abc/assets/index-DZ1_cK56.js:10
    T https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    P https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    promise callback*P https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    w https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    install https://redacted.redacted.abc/assets/index-DZ1_cK56.js:27
    use https://redacted.redacted.abc/assets/index-DZ1_cK56.js:15
    <anonymous> https://redacted.redacted.abc/assets/index-DZ1_cK56.js:137
index-DZ1_cK56.js:14:2009
```

**Comment by lewisd32** [comment]
It's maybe also worth mentioning that I see the same behaviour (empty list, ingredients paging not working) on iPhone, which is where I first registered and started trying this out. I moved to Chrome on desktop to try debugging what might be wrong.

**Comment by karlomikus** [comment]
Can you paste what you get as a response from your network tab for the main cocktails URL. Should be something like: `/bar/api/cocktails?per_page=25&page=1&sort=-created_at&&include=ratings%2Cingredients.ingredient%2Ctags%2Cimages`.

This looks like some relations are not getting loaded.

To me it looks like your webserver setup is stripping out query string from the api calls.

**Comment by lewisd32** [comment]
This is the response for `
https://redacted.redacted.abc/bar/api/cocktails?per_page=50&page=1&sort=-created_at&&include=ratings%2Cingredients.ingredient%2Ctags%2Cimages`: [cocktails-response.json](https://github.com/user-attachments/files/17937137/cocktails-response.json)

>To me it looks like your webserver setup is stripping out query string from the api calls.

This is possible... I did have to set up the nginx proxying myself, it's possible I did something wrong. Is there an easy way to enable access logs for bar assistant? I wasn't able to find any logs. If nginx is stripping the query strings, that's definitely my own problem to sort out.

**Comment by karlomikus** [comment]
Query string are definitely not getting passed to the api. This is minimal cocktail list response.

Post your nginx.conf setup, maybe I can help. From what I know, nginx strips query string [depending on the trailing slash](https://stackoverflow.com/questions/22759345/nginx-trailing-slash-in-proxy-pass-url).
